# Generated by Django 3.2.6 on 2021-09-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cashflow',
            name='kategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.cashflowcategory'),
        ),
    ]
