# Generated by Django 3.2.6 on 2021-09-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_auto_20210906_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'verbose_name': 'Arus Keuangan', 'verbose_name_plural': 'Arus Keuangan'},
        ),
        migrations.AlterModelOptions(
            name='cashflowcategory',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='harga_total',
        ),
    ]
