# Generated by Django 3.2.6 on 2021-09-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0003_auto_20210907_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='nama_item',
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='harga_satuan',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='qty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='tanggal',
            field=models.DateTimeField(null=True, verbose_name='Tanggal Transaksi'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.product'),
        ),
    ]
